[theme]
primaryColor = "#FFFFFF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#000000"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

